# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ViTuBe' do
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'SDWebImage', '~>3.6'
pod 'Google-Mobile-Ads-SDK'
pod 'SVPullToRefresh'
end

